export const FETCH_TOKEN = 'FETCH_TOKEN';
export const PRIMARY_ARTIST = 'PRIMARY_ARTIST';
export const REMOVE_PRIMARY_ARTIST = 'REMOVE_PRIMARY_ARTIST';
export const ADD_ARTIST = 'ADD_ARTIST';
export const REMOVE_ARTIST = 'REMOVE_ARTIST';
export const SUBMIT_ARTISTS_SUCCESS = 'SUBMIT_ARTISTS_SUCCESS';
export const SUBMIT_ARTISTS_FAILURE = 'SUBMIT_ARTISTS_FAILURE';
export const SUBMIT_EMAIL_SUCCESS = 'SUBMIT_EMAIL_SUCCESS';
export const SUBMIT_EMAIL_FAILURE = 'SUBMIT_EMAIL_FAILURE';

