export const FETCH_TOKEN = 'FETCH_TOKEN';
export const PRIMARY_ARTIST = 'PRIMARY_ARTIST';
export const REMOVE_PRIMARY_ARTIST = 'REMOVE_PRIMARY_ARTIST';
export const ADD_ARTIST = 'ADD_ARTIST';
export const REMOVE_ARTIST = 'REMOVE_ARTIST';
